// Mocks generated by Mockito 5.4.6 from annotations
// in employee_app/test/features/employees/presentation/bloc/employee_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:employee_app/core/failure/failure.dart' as _i7;
import 'package:employee_app/features/employees/domain/entity/employee_list_entity/employee_list_entity.dart'
    as _i8;
import 'package:employee_app/features/employees/domain/repositories/employee_repository.dart'
    as _i2;
import 'package:employee_app/features/employees/domain/repositories/job_repository.dart'
    as _i4;
import 'package:employee_app/features/employees/domain/usecases/employee_usecase.dart'
    as _i5;
import 'package:employee_app/features/employees/domain/usecases/job_post_usecase.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEmployeeRepository_0 extends _i1.SmartFake
    implements _i2.EmployeeRepository {
  _FakeEmployeeRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJobRepository_2 extends _i1.SmartFake implements _i4.JobRepository {
  _FakeJobRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EmployeeUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmployeeUsecase extends _i1.Mock implements _i5.EmployeeUsecase {
  MockEmployeeUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EmployeeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeEmployeeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.EmployeeRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.EmployeeListEntity>> fetchUser({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUser, [], {#page: page}),
            returnValue:
                _i6.Future<
                  _i3.Either<_i7.Failure, _i8.EmployeeListEntity>
                >.value(
                  _FakeEither_1<_i7.Failure, _i8.EmployeeListEntity>(
                    this,
                    Invocation.method(#fetchUser, [], {#page: page}),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, _i8.EmployeeListEntity>>);
}

/// A class which mocks [JobPostUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobPostUsecase extends _i1.Mock implements _i9.JobPostUsecase {
  MockJobPostUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.JobRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeJobRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.JobRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, String>> jobPost({
    required String? name,
    required String? job,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#jobPost, [], {#name: name, #job: job}),
            returnValue: _i6.Future<_i3.Either<_i7.Failure, String>>.value(
              _FakeEither_1<_i7.Failure, String>(
                this,
                Invocation.method(#jobPost, [], {#name: name, #job: job}),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, String>>);
}
